name: corp_illiq
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - altair>=5.1.2
  - beautifulsoup4>=4.12.2
  - doit>=0.36.0
  - ipython>=8.17.2
  - jupyter>=1.0.0
  - jupyterlab>=4.0.11
  - linearmodels>=5.3
  - matplotlib>=3.8.1
  - nbconvert>=7.14.1
  - notebook>=7.0.6
  - numpy>=1.26.0
  - openpyxl>=3.1.2
  - pandas>=2.2.0
  - pandas-datareader>=0.10.0
  - pandas-market-calendars>=4.3.1
  - plotly>=5.19.0
  - pytest>=7.4.3
  - python-decouple>=3.8
  - python-dotenv>=1.0.0
  - pyxlsb>=1.0.10
  - requests>=2.31.0
  - scikit-learn>=1.3.2
  - scipy>=1.11.3
  - seaborn>=0.13.1
  - statsmodels>=0.14.1
  - streamlit>=1.28.1
  - tqdm >= 4.66.2
  - vega_datasets>=0.9.0
  - wrds>=3.1.6
  - xbbg>=0.7.7
  - xlrd>=2.0.1
  - zstandard>=0.22.0
  - importlib>=1.0.4
  - importlib-metadata>=4.8.3
  - jsonschema>=3.0.2
  - zipp>=3.17.0
  - cloudpickle>=3.0.0