name: corp_illiq
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
name: base
dependencies:
  - alabaster>=0.7.16
  - anyio>=4.0.0
  - appdirs>=1.4.4
  - argon2-cffi>=23.1.0
  - argon2-cffi-bindings>=21.2.0
  - arrow>=1.3.0
  - asgiref>=3.7.2
  - asttokens>=2.4.1
  - async-lru>=2.0.4
  - attrs>=23.2.0
  - Babel>=2.14.0
  - beautifulsoup4>=4.12.2
  - binaryornot>=0.4.4
  - bleach>=6.1.0
  - blinker>=1.7.0
  - cachetools>=5.3.2
  - certifi>=2023.11.17
  - cffi>=1.16.0
  - chardet>=5.2.0
  - charset-normalizer>=3.3.2
  - click>=8.1.7
  - cloudpickle>=3.0.0
  - colorama>=0.4.6
  - comm>=0.2.1
  - config>=0.5.1
  - contourpy>=1.2.0
  - cookiecutter>=2.5.0
  - cycler>=0.12.1
  - debugpy>=1.8.0
  - decorator>=5.1.1
  - defusedxml>=0.7.1
  - docx>=0.2.4
  - doit>=0.36.0
  - entrypoints>=0.4
  - et-xmlfile>=1.1.0
  - exceptiongroup>=1.1.3
  - exchange_calendars>=4.5.2
  - executing>=2.0.1
  - fastjsonschema>=2.19.1
  - fonttools>=4.47.0
  - fqdn>=1.5.1
  - frozendict>=2.4.0
  - gitdb>=4.0.11
  - GitPython>=3.1.41
  - greenlet>=3.0.3
  - h11>=0.14.0
  - html5lib>=1.1
  - htmltools>=0.4.1
  - idna>=3.4
  - imagesize>=1.4.1
  - imbalanced-learn>=0.12.0
  - importlib>=1.0.4
  - importlib-metadata>=7.0.1
  - importlib-resources>=6.1.1
  - iniconfig>=2.0.0
  - ipykernel>=6.28.0
  - ipython>=8.17.2
  - ipython-genutils>=0.2.0
  - isoduration>=20.11.0
  - jedi>=0.19.1
  - Jinja2>=3.1.3
  - joblib>=1.3.2
  - json5>=0.9.14
  - jsonpointer>=2.4
  - jsonschema>=4.21.1
  - jsonschema-specifications>=2023.12.1
  - jupyter-contrib-core>=0.4.2
  - jupyter-contrib-nbextensions>=0.7.0
  - jupyter-events>=0.9.0
  - jupyter-highlight-selected-word>=0.2.0
  - jupyter-lsp>=2.2.1
  - jupyter-nbextensions-configurator>=0.6.3
  - jupyter_client>=7.4.9
  - jupyter_core>=5.7.1
  - jupyter_server>=2.12.4
  - jupyter_server_terminals>=0.5.1
  - jupyterlab>=4.0.2
  - jupyterlab_pygments>=0.3.0
  - jupyterlab_server>=2.25.2
  - kiwisolver>=1.4.5
  - korean-lunar-calendar>=0.3.1
  - linkify-it-py
